name: Scheduled Email Sender

on:
  schedule:
    - cron: '10 13 * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run email script
        run: python script.py